"""add_account_type_is_active_description

Revision ID: 60bfb260000a
Revises: 011a403fd225
Create Date: 2026-03-16 00:06:28.891539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bfb260000a'
down_revision: Union[str, Sequence[str], None] = '011a403fd225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adiciona account_type, description e is_active à tabela contas.

    Contas existentes recebem account_type='conta_bancaria' e is_active=True como default.
    """
    op.add_column('contas', sa.Column('account_type', sa.String(length=32), nullable=False, server_default='conta_bancaria'))
    op.add_column('contas', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('contas', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas', 'is_active')
    op.drop_column('contas', 'description')
    op.drop_column('contas', 'account_type')
    # ### end Alembic commands ###
