"""add_compartilhamentos_table

Revision ID: be2a52eb5b28
Revises: 2f2cd02a416a
Create Date: 2026-03-16 22:43:33.603619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2a52eb5b28'
down_revision: Union[str, Sequence[str], None] = '2f2cd02a416a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compartilhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'reader_id', name='uq_share_owner_reader')
    )
    op.create_index(op.f('ix_compartilhamentos_owner_id'), 'compartilhamentos', ['owner_id'], unique=False)
    op.create_index(op.f('ix_compartilhamentos_reader_id'), 'compartilhamentos', ['reader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compartilhamentos_reader_id'), table_name='compartilhamentos')
    op.drop_index(op.f('ix_compartilhamentos_owner_id'), table_name='compartilhamentos')
    op.drop_table('compartilhamentos')
    # ### end Alembic commands ###
